[book]
authors = ["Jeff Mendez"]
language = "en"
src = "src"
title = "spider-py"

[output.html]
git-repository-url = "https://github.com/spider-rs/spider-py/tree/main/book"
edit-url-template  = "https://github.com/spider-rs/spider-py/edit/main/book/{path}"
